name: Backend Continuous Integration

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      # Install dependencies
      - run: pip install pipenv
      - run: cd starter/backend && pipenv install 

      - run: echo $PWD

      # Linting
      - run: pipenv run lint ./starter/backend/movies/
  
  testing-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      # Install dependencies
      - run: pip install pipenv
      - run: cd starter/backend && pipenv install 

      # Testing
      - run: cd starter/backend && pipenv run test
  
  build:
    needs: [linting-job, testing-job]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      # Install dependencies
      - run: pip install pipenv
      - run: cd starter/backend && pipenv install

      # Build
      - run: cd starter/backend && docker build -t backend-img .