name: My First Workflow

# Trigger: Manual or Automatic or Scheduled Trigger
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 5 * * 1-5'

# Job: include multiple tasks and can use environment variables
jobs:
  build:
    runs-on: ubuntu-latest

    # Small Unit -> combine logics 
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Print a message
      run: echo "Hello, world!"